name: Build wheels

on: 
  # push:
   workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, macos-13]

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.3
        env:
          CIBW_BEFORE_ALL: >
               cd /tmp/ &&
               git clone https://github.com/kimwalisch/primecount &&
               cd primecount &&
               export CXXFLAGS="-fPIC" &&
               export LDFLAGS="-fPIC"
          
          CIBW_BEFORE_BUILD_LINUX: >
               cd /tmp/primecount &&
               cmake . -DWITH_OPENMP=OFF -DCMAKE_VERBOSE_MAKEFILE=TRUE -DBUILD_SHARED_LIBS=ON -DBUILD_STATIC_LIBS=OFF &&
               make && make install

          CIBW_BEFORE_BUILD_MACOS: >
               cd /tmp/primecount &&
               cmake . -DWITH_OPENMP=OFF -DCMAKE_VERBOSE_MAKEFILE=TRUE -DBUILD_SHARED_LIBS=OFF -DBUILD_STATIC_LIBS=ON &&
               make && sudo make install

          CIBW_SKIP: pp*

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
